

###### For NLB

apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: aws-nlb 
  
  ## Donot work but the logic is  same as write just need to include that in the spec.parametersRef not 
  ## in annotationos.

  # annotations:
  #   gateway.k8s.aws/loadBalancerConfiguration: public-nlb -config

spec:
  controllerName: gateway.k8s.aws/nlb 
  parametersRef:
    group: gateway.k8s.aws
    kind: LoadBalancerConfiguration
    name: public-nlb-config
    namespace: default


--- 


apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-api
  namespace: default

  ## Not needed ( Even though mentioned in the DOCS and Donot Work )
  ## can be done using the same spec.infrastructure.parametersRef.

  # annotations: 
  #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb "
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  gatewayClassName: aws-nlb 
  infrastructure:
    parametersRef:
      group: gateway.k8s.aws
      kind: LoadBalancerConfiguration
      name: public-nlb-config


  listeners:
    - name: tcp-80
      protocol: TCP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

    - name: tcp-443
      protocol: TCP
      port: 443
      allowedRoutes:
        namespaces:
          from: All  

--- 


apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: public-nlb-config 
  namespace: default       
spec:
  scheme: internet-facing 
#  ipAddressType: ipv4
  listenerConfigurations:
    - protocolPort: HTTPS:443
      defaultCertificate: arn:aws:acm:us-east-1:702865854817:certificate/0a2a90bc-1d29-4205-a639-acb43b18a7be
 



--- 



apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: my-tcp-route
  namespace: default
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway-api
    namespace: default
    sectionName: tcp-80
  rules:
  - backendRefs:
    - name: service
      port: 80

---

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: my-tcp-route-443
  namespace: default
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway-api
    namespace: default
    sectionName: tcp-443
  rules:
  - backendRefs:
    - name: service
      port: 80


--- 


apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80 
    # nodePort: 30070 
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        
        ports:
        - containerPort: 80

--- 


apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: example-tg-config
  namespace: default
spec:
  targetReference:
    name: service
    kind: Service
    group: ""        # core/v1
  defaultConfiguration:
    # port: 80
    targetType: ip
    protocol: TCP
    ipAddressType: ipv4




### FOR ALB 

# apiVersion: gateway.networking.k8s.io/v1
# kind: GatewayClass
# metadata:
#   name: aws-alb
  
#   ## Donot work but the logic is  same as write just need to include that in the spec.parametersRef not 
#   ## in annotationos.

#   # annotations:
#   #   gateway.k8s.aws/loadBalancerConfiguration: public-alb-config

# spec:
#   controllerName: gateway.k8s.aws/alb
#   parametersRef:
#     group: gateway.k8s.aws
#     kind: LoadBalancerConfiguration
#     name: public-alb-config
#     namespace: default






# --- 


# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: gateway-api
#   namespace: default

#   ## Not needed ( Even though mentioned in the DOCS and Donot Work )
#   ## can be done using the same spec.infrastructure.parametersRef.

#   # annotations: 
#   #   service.beta.kubernetes.io/aws-load-balancer-type: "alb"
#   #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
# spec:
#   gatewayClassName: aws-alb
#   infrastructure:
#     parametersRef:
#       group: gateway.k8s.aws
#       kind: LoadBalancerConfiguration
#       name: public-alb-config


#   listeners:
#     - name: http
#       protocol: HTTP
#       port: 80
#       allowedRoutes:
#         namespaces:
#           from: All  

# --- 


# apiVersion: gateway.k8s.aws/v1beta1
# kind: LoadBalancerConfiguration
# metadata:
#   name: public-alb-config 
#   namespace: default       
# spec:
#   scheme: internet-facing 
#   ipAddressType: ipv4
 



# --- 



# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: my-route
#   namespace: default
# spec:
#   parentRefs:
#   - kind: Gateway
#     name: gateway-api
#     namespace: default
#   rules:
#   - backendRefs:
#     - name: service
#       port: 80


# --- 


# apiVersion: v1
# kind: Service
# metadata:
#   name: service
# spec:
#   type: ClusterIP

#   selector:
#     app: myapp
#   ports:
#   - port: 80
#     targetPort: 80 
#     nodePort: 30080  
# --- 

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: myapp
# spec:
#   selector:
#     matchLabels:
#       app: myapp
#   template:
#     metadata:
#       labels:
#         app: myapp
#     spec:
#       replicas: 3 
#       containers:
#       - name: myapp
#         image: nginx:latest
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "250m"
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 80




# --- 



# apiVersion: gateway.k8s.aws/v1beta1
# kind: TargetGroupConfiguration
# metadata:
#   name: example-tg-config
#   namespace: default
# spec:
#   targetReference:
#     name: service
#     kind: Service
#     group: ""        # core/v1
#   defaultConfiguration:
#     targetType: instance
#     protocol: HTTP
#     ipAddressType: ipv4





